name: Unit Tests

on: push

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v2
    
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1.0.5
    - name: Restore NuGet package
      run: |
        nuget restore ./NugetRestoreFail/NugetRestoreFail.csproj
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Run Unit Test suite
      run: dotnet test ./NugetRestoreFail/NugetRestoreFail.csproj
